# Generated by Django 4.0.3 on 2023-03-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecentlyView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_date', models.DateTimeField(auto_now=True)),
                ('search_topic', models.CharField(max_length=200)),
                ('feedback', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topicname', models.CharField(max_length=200)),
                ('context', models.TextField()),
                ('example', models.TextField()),
            ],
        ),
    ]
